 workflows:
  ios-build:
    name: iOS Build (No Publish)
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.simpleApp"  # <- Change this to your actual iOS bundle ID
    triggering:
      events:
        - push
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Build iOS release
        script: |
          flutter build ios --release --no-codesign
      - name: Flutter build ipa
        script: | 
          flutter build ipa --release 
          

    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/Runner.app
      - build/ios/archive/*.xcarchive

